const SKILLS_DATA=[
{name:'data-export-plus',displayName:'Advanced Data Export',description:'Export data into Parquet, Feather, JSON Lines, and other warehouse-friendly formats.',version:'1.2.0',author:'SocialHub Official',category:'data',downloads:15680,rating:4.8,tags:['export','parquet','data-format'],icon:'DX',permissions:['file:write','data:read'],commands:[{name:'export-parquet',description:'Export data in Parquet format'},{name:'export-feather',description:'Export data in Feather format'},{name:'export-jsonl',description:'Export data in JSON Lines format'}],readme:'A production-oriented export toolkit for large datasets, analytics workflows, and downstream warehousing.'},
{name:'wechat-analytics',displayName:'WeChat Analytics',description:'Analyze WeChat channel behavior, funnel progression, and private-domain engagement in one package.',version:'2.1.0',author:'SocialHub Official',category:'analytics',downloads:28450,rating:4.9,tags:['wechat','analytics','funnel'],icon:'WC',permissions:['data:read','network:internet'],commands:[{name:'wechat-overview',description:'Open a WeChat channel overview'},{name:'wechat-funnel',description:'Inspect conversion funnel performance'},{name:'wechat-users',description:'Review user behavior segments'}],readme:'Designed for WeChat-heavy teams that need a fast read on retention, interaction quality, and funnel leakage.'},
{name:'campaign-optimizer',displayName:'Campaign Optimizer',description:'Use historical campaign data to improve ROI, scheduling, and audience timing decisions.',version:'1.5.0',author:'SocialHub Official',category:'marketing',downloads:12300,rating:4.7,tags:['campaign','optimization','ai'],icon:'AI',permissions:['data:read','data:write'],commands:[{name:'optimize',description:'Optimize campaign setup'},{name:'suggest-time',description:'Recommend the best send time'},{name:'predict-roi',description:'Estimate campaign ROI'}],readme:'Turns campaign history into practical suggestions for budget allocation, send cadence, and performance recovery.'},
{name:'report-generator',displayName:'Report Generator',description:'Generate multi-section business reports with scheduling and export support built in.',version:'1.1.0',author:'SocialHub Official',category:'utility',downloads:21000,rating:4.8,tags:['report','automation','schedule'],icon:'RP',permissions:['data:read','file:write'],commands:[{name:'report-create',description:'Create a report template'},{name:'report-generate',description:'Generate a report'},{name:'report-schedule',description:'Schedule recurring output'}],readme:'A flexible reporting skill for KPI summaries, executive snapshots, and scheduled stakeholder updates.'}
];
let currentCategory='all';let currentSort='downloads';let searchQuery='';
const skillsGrid=document.getElementById('skillsGrid');const searchInput=document.getElementById('searchInput');const searchBtn=document.getElementById('searchBtn');const categoryTabs=document.getElementById('categoryTabs');const sortSelect=document.getElementById('sortSelect');const skillModal=document.getElementById('skillModal');const modalBody=document.getElementById('modalBody');const modalClose=document.getElementById('modalClose');const cliBtn=document.getElementById('cliBtn');const cliModal=document.getElementById('cliModal');const cliModalClose=document.getElementById('cliModalClose');
document.addEventListener('DOMContentLoaded',()=>{renderSkills();setupEventListeners();});
function setupEventListeners(){searchBtn?.addEventListener('click',handleSearch);searchInput?.addEventListener('keypress',(e)=>{if(e.key==='Enter')handleSearch();});categoryTabs?.addEventListener('click',(e)=>{const tab=e.target.closest('.category-tab');if(!tab)return;document.querySelectorAll('.category-tab').forEach((i)=>i.classList.remove('active'));tab.classList.add('active');currentCategory=tab.dataset.category;renderSkills();});sortSelect?.addEventListener('change',(e)=>{currentSort=e.target.value;renderSkills();});modalClose?.addEventListener('click',closeSkillModal);skillModal?.querySelector('.modal-overlay')?.addEventListener('click',closeSkillModal);cliBtn?.addEventListener('click',()=>cliModal.classList.add('active'));cliModalClose?.addEventListener('click',()=>cliModal.classList.remove('active'));cliModal?.querySelector('.modal-overlay')?.addEventListener('click',()=>cliModal.classList.remove('active'));document.addEventListener('click',(e)=>{if(!e.target.classList.contains('copy-btn'))return;navigator.clipboard.writeText(e.target.dataset.code).then(()=>{const old=e.target.textContent;e.target.textContent='Copied';setTimeout(()=>e.target.textContent=old,1200);});});document.addEventListener('keydown',(e)=>{if(e.key==='Escape'){closeSkillModal();cliModal?.classList.remove('active');}});}
function handleSearch(){searchQuery=(searchInput?.value||'').trim().toLowerCase();renderSkills();}
function getFilteredSkills(){let skills=[...SKILLS_DATA];if(currentCategory!=='all')skills=skills.filter((s)=>s.category===currentCategory);if(searchQuery)skills=skills.filter((s)=>[s.name,s.displayName,s.description,...s.tags].join(' ').toLowerCase().includes(searchQuery));skills.sort((a,b)=>currentSort==='rating'?b.rating-a.rating:currentSort==='newest'?b.version.localeCompare(a.version,undefined,{numeric:true}):b.downloads-a.downloads);return skills;}
function renderSkills(){if(!skillsGrid)return;const skills=getFilteredSkills();skillsGrid.innerHTML=skills.map((skill)=>`<article class="skill-card"><div class="skill-card-head"><div class="skill-card-icon">${skill.icon}</div><div><h3>${skill.displayName}</h3><p class="skill-author">${skill.author}</p></div></div><p class="skill-description">${skill.description}</p><div class="skill-meta"><span class="meta-chip">${skill.category}</span><span class="meta-chip">${skill.version}</span><span class="meta-chip">Rating ${skill.rating.toFixed(1)}</span></div><div class="skill-footer"><span>${skill.downloads.toLocaleString()} downloads</span><button class="btn btn-primary btn-sm" onclick="openSkillModal('${skill.name}')">View details</button></div></article>`).join('');}
function openSkillModal(name){const skill=SKILLS_DATA.find((s)=>s.name===name);if(!skill||!modalBody||!skillModal)return;modalBody.innerHTML=`<div class="skill-modal"><div class="skill-card-head" style="margin-bottom:18px;"><div class="skill-card-icon">${skill.icon}</div><div><h2 style="color:var(--primary);margin-bottom:6px;">${skill.displayName}</h2><p class="drawer-muted">${skill.author} | version ${skill.version}</p></div></div><p style="color:var(--text-secondary);margin-bottom:18px;">${skill.description}</p><div class="section-head"><h3 style="font-size:18px;">Commands</h3><span>${skill.commands.length} entries</span></div><div class="stack-list">${skill.commands.map((c)=>`<div class="stack-item"><strong>${c.name}</strong><div class="drawer-muted">${c.description}</div></div>`).join('')}</div><div class="section-head" style="margin-top:18px;"><h3 style="font-size:18px;">Permissions</h3><span>Declared runtime scope</span></div><div class="stack-list">${skill.permissions.map((p)=>`<div class="stack-item">${p}</div>`).join('')}</div><div class="section-head" style="margin-top:18px;"><h3 style="font-size:18px;">Readme summary</h3><span>Prototype excerpt</span></div><div class="stack-item">${skill.readme}</div></div>`;skillModal.classList.add('active');}
function closeSkillModal(){skillModal?.classList.remove('active');}
window.openSkillModal=openSkillModal;
