"""add credential_type, make customer_id nullable

Revision ID: 4feacdde6079
Revises: 8623e725a88b
Create Date: 2026-03-31 15:42:56.206107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4feacdde6079'
down_revision: Union[str, Sequence[str], None] = '8623e725a88b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant_bigquery_credentials', sa.Column('credential_type', sa.String(length=50), nullable=False))
    op.alter_column('tenant_bigquery_credentials', 'customer_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenant_bigquery_credentials', 'customer_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('tenant_bigquery_credentials', 'credential_type')
    # ### end Alembic commands ###
