apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: skills-store-packages
  labels:
    app.kubernetes.io/name: socialhub-skills-store
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: socialhub
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: skills-store-secrets-vol
  labels:
    app.kubernetes.io/name: socialhub-skills-store
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: socialhub
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi